FROM node:14

WORKDIR /app

COPY package.json .

RUN npm install

COPY . .

ARG DEFAULT_PORT=80
# CANNOT BE USED IN COMMAND BUT CAN BE USED IN ALL OTHER INSTRUCIONS

ENV PORT=$DEFAULT_PORT

EXPOSE $PORT 
# THE DOLAR SIGN IS USED TO MARK AN ENVIORMENT VARIABLE

# VOLUME [ "/app/node_modules" ]

VOLUME ["/temp"]

CMD [ "npm", "start" ]